
CREATE WAREHOUSE IF NOT EXISTS ELEC_FORECAST_WH
  WAREHOUSE_SIZE = 'XSMALL'  -- bc its cheap
  AUTO_SUSPEND = 60          
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ELEC_FORECAST;

USE DATABASE ELEC_FORECAST;

CREATE SCHEMA IF NOT EXISTS BRONZE;   -- miror of local data
CREATE SCHEMA IF NOT EXISTS SILVER;   -- output from spark_jobs/build_silver.py (cleaned and joined)
CREATE SCHEMA IF NOT EXISTS GOLD;     -- star schema ready to go 

-- intern stage bc its local development for now (no S3 yet)
CREATE STAGE IF NOT EXISTS BRONZE.LANDING_STAGE
  FILE_FORMAT = (TYPE = PARQUET);

CREATE ROLE IF NOT EXISTS ELEC_FORECAST_LOADER;
GRANT USAGE ON WAREHOUSE ELEC_FORECAST_WH TO ROLE ELEC_FORECAST_LOADER;
GRANT USAGE ON DATABASE ELEC_FORECAST TO ROLE ELEC_FORECAST_LOADER;
GRANT ALL ON SCHEMA BRONZE TO ROLE ELEC_FORECAST_LOADER;
GRANT ALL ON SCHEMA SILVER TO ROLE ELEC_FORECAST_LOADER;
GRANT ALL ON SCHEMA GOLD TO ROLE ELEC_FORECAST_LOADER;
GRANT ROLE ELEC_FORECAST_LOADER TO USER arslane18;
