USE DATABASE ELEC_FORECAST;
USE SCHEMA BRONZE;


CREATE TABLE IF NOT EXISTS ECO2MIX_REGIONAL (
    DATE_HEURE           TIMESTAMP_NTZ NOT NULL,
    DATE                 DATE,
    CODE_INSEE_REGION    VARCHAR(10)   NOT NULL,
    LIBELLE_REGION       VARCHAR(100),
    NATURE               VARCHAR(50),
    CONSOMMATION         FLOAT,
    PRIMARY KEY (DATE_HEURE, REGION_CODE)
);


CREATE TABLE IF NOT EXISTS OPENMETEO (
    TIME                 TIMESTAMP_NTZ NOT NULL,
    REGION_CODE          NUMBER        NOT NULL,
    TEMPERATURE_2M       FLOAT,
    PRECIPITATION        FLOAT,
    PRIMARY KEY (TIME, REGION_CODE)
);

CREATE TABLE IF NOT EXISTS PUBLIC_HOLIDAYS (
    REGION_CODE          NUMBER        NOT NULL,
    DATE                 DATE          NOT NULL,
    JOUR_FERIE           VARCHAR(100),
    IS_HOLIDAY           INT,
    PRIMARY KEY (DATE, REGION_CODE)
);


