USE DATABASE ELEC_FORECAST;
USE SCHEMA SILVER;

CREATE TABLE IF NOT EXISTS CONSO_METEO_HORAIRE (
    DATE_HEURE        TIMESTAMP_NTZ NOT NULL,
    REGION_CODE       NUMBER        NOT NULL,
    CONSOMMATION      FLOAT,
    TEMPERATURE_2M    FLOAT,
    PRECIPITATION     FLOAT,
    IS_HOLIDAY        INT       DEFAULT 0,
    YEAR              INT,
    PRIMARY KEY (DATE_HEURE, REGION_CODE)
);
