USE DATABASE ELEC_FORECAST;


-- 1. Duplicates: (DATE_HEURE, REGION_CODE) must be unique
SELECT DATE_HEURE, REGION_CODE, COUNT(*) AS nb
FROM SILVER.CONSO_METEO_HORAIRE
GROUP BY 1, 2
HAVING COUNT(*) > 1;

-- 2. Gaps: hourly series shouldn't skip more than one hour per region
SELECT REGION_CODE, DATE_HEURE,
       DATEDIFF('hour', LAG(DATE_HEURE) OVER (PARTITION BY REGION_CODE ORDER BY DATE_HEURE), DATE_HEURE) AS ecart_h
FROM SILVER.CONSO_METEO_HORAIRE
QUALIFY ecart_h > 2;

-- 3. Freshness: each region's latest row shouldn't be older than 48h
SELECT REGION_CODE, MAX(DATE_HEURE) AS derniere_donnee
FROM SILVER.CONSO_METEO_HORAIRE
GROUP BY REGION_CODE
HAVING DATEDIFF('hour', derniere_donnee, CURRENT_TIMESTAMP()) > 48;

-- 4. Outliers: CONSOMMATION must be a plausible, non-null, non-negative MW value
SELECT DATE_HEURE, REGION_CODE, CONSOMMATION
FROM SILVER.CONSO_METEO_HORAIRE
WHERE CONSOMMATION IS NULL OR CONSOMMATION < 0 OR CONSOMMATION > 50000;
